export const USER_LOGGEDIN_SUCCESS = "USER_LOGGEDIN_SUCCESS";
export const USER_LOGGEDOUT_SUCCESS = "USER_LOGGEDOUT_SUCCESS";

export const LOAD_STORES_SUCCESS = "LOAD_STORES_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";