export const USER_LOGGEDIN_SUCCESS = "USER_LOGGEDIN_SUCCESS";
export const USER_LOGGEDOUT_SUCCESS = "USER_LOGGEDOUT_SUCCESS";

export const LOAD_STORES_SUCCESS = "LOAD_STORES_SUCCESS";
export const LOAD_STORES_FAIL = "LOAD_STORES_FAIL";

export const SAVE_STORE_SUCCESS = "SAVE_STORE_SUCCESS";
export const SAVE_STORE_FAIL = "SAVE_STORE_FAIL";

// export const SAVE_STORE_PHOTOS_SUCCESS = "SAVE_STORE_PHOTOS_SUCCESS";
// export const SAVE_STORE_PHOTOS_FAIL = "SAVE_STORE_PHOTOS_FAIL";

export const BEGIN_API_CALL = "BEGIN_API_CALL";